/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.datatheorem.sast;

public class App {
    public String getGreeting() {
		System.out.println("This token is sensitive and should not be committed to version control: AKIAIOSFODNN7EXAMPLE");
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
